const galleryOne = [
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_1_elixib.avif",
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_tbchum.avif",
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_2_gzls5q.avif",
];

const galleryTwo = [
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_nl0mgr.avif",
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_2_allwc1.avif",
  "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_1_efbbiz.avif",
];

export const assetLibrary = [
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_1_elixib.avif", label: "Latgab Pramuka MAN 3 (1)" },
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_tbchum.avif", label: "Latgab Pramuka MAN 3 (2)" },
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.48_2_gzls5q.avif", label: "Latgab Pramuka MAN 3 (3)" },
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_nl0mgr.avif", label: "Latgab PMR & Pramuka (1)" },
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_2_allwc1.avif", label: "Latgab PMR & Pramuka (2)" },
  { path: "/gudang/gallery/latgab/WhatsApp_Image_2026-02-02_at_21.17.49_1_efbbiz.avif", label: "Latgab PMR & Pramuka (3)" },
  { path: "/gudang/gallery/IMG-20260129-WA0031_icpj2a_fqfute.avif", label: "Aksi Kebersamaan (1)" },
  { path: "/gudang/gallery/IMG-20260129-WA0032_p6mnxz_ggclja.avif", label: "Aksi Kebersamaan (2)" },
  { path: "/gudang/gallery/IMG-20260129-WA0035_fwkslt_jjng7f.avif", label: "Aksi Kebersamaan (3)" },
  { path: "/gudang/gallery/IMG-20260129-WA0037_ywu4kh_eldskn.avif", label: "Latihan Keterampilan" },
  { path: "/gudang/gallery/juara.avif", label: "Foto Juara / Prestasi" },
  { path: "/gudang/gallery/pixnova-8ec1cb637215f0ce9cd86e4da3453792_gcss38.avif", label: "Ilustrasi Aksi" },
  { path: "/gudang/org/wakil_1782458849_771dbdcc.jpeg", label: "Foto Wakil Ketua" },
  { path: "/gudang/org/wakil_sekretaris_1784116447_104d55b6.jpeg", label: "Foto Sekretaris" },
  { path: "/gudang/org/kord_1784120541_e1bb0122.jpeg", label: "Foto Kord Humas" },
  { path: "/gudang/logo/pmr-logo.webp", label: "Logo PMR Wira" },
];

export const defaultRoster = {
  periode: "Agustus 2026",
  bulan_label: "Agustus 2026",
  keterangan: "Jadwal resmi penjagaan Ruang UKS (Senin–Jumat) dan piket lapangan upacara (Setiap Senin) untuk seluruh anggota aktif PMR Wira SMKN 4 Banjarmasin.",
  petugas_per_shift_uks: 2,
  petugas_per_shift_lapangan: 4,
  uks_schedule: [
    { tanggal: "Senin, 3 Agustus 2026", hari: "Senin", petugas: ["Syifa Maurinjia", "Nazma Az Zahra"] },
    { tanggal: "Selasa, 4 Agustus 2026", hari: "Selasa", petugas: ["Nahdhah", "Andi Nabilla Ramadani"] },
    { tanggal: "Rabu, 5 Agustus 2026", hari: "Rabu", petugas: ["Maulidia Hayuningdiah", "Naufa Azmi Khairizqa"] },
    { tanggal: "Kamis, 6 Agustus 2026", hari: "Kamis", petugas: ["Melsia Oktavia", "Eva Regina Putri Riyanti"] },
    { tanggal: "Jumat, 7 Agustus 2026", hari: "Jumat", petugas: ["Lisa Erfina", "Naylah Azkiya"] },
    { tanggal: "Senin, 10 Agustus 2026", hari: "Senin", petugas: ["Rama", "Alia Rahmawati"] },
    { tanggal: "Selasa, 11 Agustus 2026", hari: "Selasa", petugas: ["Ferdi Herlino", "Almira Fakhriah Hasan"] },
    { tanggal: "Rabu, 12 Agustus 2026", hari: "Rabu", petugas: ["A. Ustman Abdullah", "Kirani"] },
    { tanggal: "Kamis, 13 Agustus 2026", hari: "Kamis", petugas: ["Halissa Azzahra", "Delya Ananda"] },
    { tanggal: "Jumat, 14 Agustus 2026", hari: "Jumat", petugas: ["Lionel Abdi Darma W.", "Selviana Dewi"] },
    { tanggal: "Senin, 17 Agustus 2026", hari: "Senin", petugas: ["Muhammad Sultan Ariady", "Nur Aleesya Nashirah"] },
    { tanggal: "Selasa, 18 Agustus 2026", hari: "Selasa", petugas: ["Nabila Rosydah Zahro", "Zahrah Fitri Aisy"] },
    { tanggal: "Rabu, 19 Agustus 2026", hari: "Rabu", petugas: ["Wulandari", "Lietya Aisya"] },
    { tanggal: "Kamis, 20 Agustus 2026", hari: "Kamis", petugas: ["Firy al Humairoh Rahmah", "Sofha Raihana Kamelia"] },
    { tanggal: "Jumat, 21 Agustus 2026", hari: "Jumat", petugas: ["Syifa Maurinjia", "Andi Nabilla Ramadani"] },
    { tanggal: "Senin, 24 Agustus 2026", hari: "Senin", petugas: ["Nazma Az Zahra", "Nahdhah"] },
    { tanggal: "Selasa, 25 Agustus 2026", hari: "Selasa", petugas: ["Maulidia Hayuningdiah", "Melsia Oktavia"] },
    { tanggal: "Rabu, 26 Agustus 2026", hari: "Rabu", petugas: ["Naufa Azmi Khairizqa", "Eva Regina Putri Riyanti"] },
    { tanggal: "Kamis, 27 Agustus 2026", hari: "Kamis", petugas: ["Lisa Erfina", "Rama"] },
    { tanggal: "Jumat, 28 Agustus 2026", hari: "Jumat", petugas: ["Naylah Azkiya", "Alia Rahmawati"] },
    { tanggal: "Senin, 31 Agustus 2026", hari: "Senin", petugas: ["Ferdi Herlino", "A. Ustman Abdullah"] },
  ],
  lapangan_schedule: [
    { tanggal: "Senin, 3 Agustus 2026", hari: "Senin", petugas: ["Kirani", "Halissa Azzahra", "Delya Ananda", "Lionel Abdi Darma W."] },
    { tanggal: "Senin, 10 Agustus 2026", hari: "Senin", petugas: ["Selviana Dewi", "Muhammad Sultan Ariady", "Nur Aleesya Nashirah", "Nabila Rosydah Zahro"] },
    { tanggal: "Senin, 17 Agustus 2026", hari: "Senin", petugas: ["Zahrah Fitri Aisy", "Wulandari", "Lietya Aisya", "Firy al Humairoh Rahmah"] },
    { tanggal: "Senin, 24 Agustus 2026", hari: "Senin", petugas: ["Sofha Raihana Kamelia", "Syifa Maurinjia", "Andi Nabilla Ramadani", "Nazma Az Zahra"] },
    { tanggal: "Senin, 31 Agustus 2026", hari: "Senin", petugas: ["Nahdhah", "Maulidia Hayuningdiah", "Melsia Oktavia", "Naufa Azmi Khairizqa"] },
  ],
  is_published: true,
  updated_at: "2026-07-17T11:00:00Z"
};

export const defaultUksInfo = {
  welcome_banner: {
    title: "Ruang UKS Terbuka untuk Seluruh Siswa-Siswi",
    subtitle: "Merasa kurang sehat, pusing, demam, atau butuh pertolongan pertama saat berada di sekolah? Jangan ragu untuk datang ke Ruang UKS SMKN 4 Banjarmasin.",
    highlight: "Semua pemeriksaan dasar dan obat-obatan P3K di Ruang UKS disediakan secara 100% GRATIS untuk seluruh siswa-siswi aktif."
  },
  jam_layanan: "Senin – Jumat selama jam pelajaran berlangsung (07.00 – 15.30 WITA)",
  lokasi: "Lantai 1 Ruang UKS SMKN 4 Banjarmasin (Dekat lapangan utama / Kantor guru)",
  stok_obat_dan_alat: [
    { id: 1, kategori: "Obat Minum Ringan", nama: "Paracetamol / Tablet Pereda Nyeri & Demam", kegunaan: "Meredakan sakit kepala, pusing, demam ringan, dan nyeri otot akut.", status: "Tersedia & Gratis" },
    { id: 2, kategori: "Obat Minum Ringan", nama: "Promag / Obat Maag & Asam Lambung", kegunaan: "Meredakan nyeri ulu hati, kembung, perih, dan mual akibat telat makan.", status: "Tersedia & Gratis" },
    { id: 3, kategori: "Obat Luar & Cairan", nama: "Minyak Kayu Putih & Minyak Angin Aromatherapi", kegunaan: "Meredakan perut kembung, masuk angin, mual ringan, dan gigitan serangga.", status: "Tersedia & Gratis" },
    { id: 4, kategori: "Obat Luar & Cairan", nama: "Povidone Iodine (Betadine) & Cairan Antiseptik", kegunaan: "Membersihkan, mensterilkan, dan mencegah infeksi pada luka gores, lecet, atau luka jatuh.", status: "Tersedia & Gratis" },
    { id: 5, kategori: "Obat Luar & Cairan", nama: "Alkohol 70% & Cairan Pembersih Luka (NaCl 0.9%)", kegunaan: "Sterilisasi area luka atau pembersih kotoran sebelum dibalut perban steril.", status: "Tersedia & Gratis" },
    { id: 6, kategori: "Obat Luar & Cairan", nama: "Salep Luka Bakar (Bioplacenton / Burnazin)", kegunaan: "Pertolongan pertama pada luka bakar ringan, terkena knalpot, atau air panas.", status: "Tersedia & Gratis" },
    { id: 7, kategori: "Obat Luar & Cairan", nama: "Krim Meredakan Memar / Thrombophob & Ethylchloride Spray", kegunaan: "Meredakan pembengkakan kronis, memar akibat benturan fisik atau olahraga.", status: "Tersedia & Gratis" },
    { id: 8, kategori: "Perban & P3K", nama: "Kasa Steril, Plester & Perban Gulung Berbagai Ukuran", kegunaan: "Menutup dan melindungi luka terbuka agar tetap bersih dari debu dan bakteri.", status: "Tersedia & Gratis" },
    { id: 9, kategori: "Perban & P3K", nama: "Mitella (Kain Segitiga P3K) & Bidai / Spalk Kayu", kegunaan: "Fiksasi darurat saat terjadi cedera terkilir, keseleo berat, atau dugaan patah tulang.", status: "Tersedia & Gratis" },
    { id: 10, kategori: "Alat Medis Dasar", nama: "Termometer Digital & Tensi Darah (Sphygmomanometer)", kegunaan: "Pemeriksaan akurat tanda vital (suhu tubuh & tekanan darah) oleh petugas UKS.", status: "Tersedia & Gratis" },
    { id: 11, kategori: "Alat Medis Dasar", nama: "Oxymeter & Tabung Oksigen Portable (Oxycan)", kegunaan: "Bantuan darurat pernapasan bagi siswa yang mengalami sesak napas, asma, atau kelelahan berat.", status: "Tersedia & Gratis" },
    { id: 12, kategori: "Fasilitas Istirahat", nama: "Tempat Tidur Istirahat UKS & Tandu Darurat", kegunaan: "Fasilitas baring sementara bagi siswa yang pingsan, kram perut, atau sakit sebelum penjemputan.", status: "Tersedia & Gratis" }
  ],
  prosedur_kunjungan: [
    { step: "Izin Guru Mata Pelajaran", deskripsi: "Minta izin secara sopan kepada guru yang sedang mengajar di kelas sebelum menuju ke Ruang UKS." },
    { step: "Lapor kepada Petugas Jaga UKS", deskripsi: "Saat tiba di Ruang UKS, laporkan keluhan medis atau gejala yang kamu rasakan kepada petugas PMR atau Pembina yang bertugas." },
    { step: "Pemeriksaan & Pemberian Obat Gratis", deskripsi: "Petugas akan memeriksa kondisi vital dasar (seperti suhu atau tensi) dan memberikan obat minum/luar sesuai keluhan secara 100% gratis." },
    { step: "Istirahat Sementara atau Surat Rujukan", deskripsi: "Jika butuh baring, siswa dipersilakan beristirahat di ranjang UKS. Jika kondisi membutuhkan penanganan medis intensif, sekolah akan menghubungi orang tua untuk penjemputan." }
  ],
  tata_tertib: [
    "Ruang UKS diperuntukkan khusus bagi siswa-siswi yang benar-benar membutuhkan pertolongan kesehatan atau istirahat medis.",
    "Dilarang membuat keributan, makan/minum berat, atau berkumpul/nongkrong di dalam Ruang UKS.",
    "Jaga kebersihan ranjang, sprei, tirai, dan peralatan P3K setelah selesai digunakan.",
    "Pengambilan obat wajib seizin dan dicatat oleh petugas/pembina UKS demi keselamatan dosis dan riwayat alergi."
  ]
};

export const fallbackContent = {
  source: "demo",
  stats: [
    { value: 642, label: "Total alumni", icon: "users" },
    { value: 120, label: "Relawan aktif", icon: "user-round-check" },
    { value: 56, label: "Aksi sosial", icon: "heart-handshake" },
  ],
  announcements: [
    {
      id: "news-1",
      category: "Latihan gabungan",
      title: "Latgab bersama Pramuka MAN 3 Banjarmasin",
      excerpt: "Mempererat silaturahmi sekaligus mengasah keterampilan pertolongan pertama antarorganisasi.",
      date: "16 Januari 2026",
      image: galleryOne[0],
      is_published: true,
    },
    {
      id: "news-2",
      category: "Kabar PMR",
      title: "PMR Wira terus bergerak untuk kemanusiaan",
      excerpt: "Dari latihan rutin hingga aksi sosial, setiap anggota belajar hadir dan memberi dampak.",
      date: "Kabar terbaru",
      image: "/gudang/gallery/juara.avif",
      is_published: true,
    },
    {
      id: "news-3",
      category: "Dokumentasi",
      title: "Belajar, berlatih, dan tumbuh bersama",
      excerpt: "Dokumentasi kegiatan anggota PMR Wira SMKN 4 Banjarmasin.",
      date: "Arsip kegiatan",
      image: "/gudang/gallery/IMG-20260129-WA0032_p6mnxz_ggclja.avif",
      is_published: true,
    },
  ],
  events: [
    {
      id: "event-1",
      title: "Latihan rutin PMR",
      date: "Setiap Kamis",
      time: "15.00–17.00 WITA",
      location: "Aula / lapangan sekolah",
      description: "Latihan keterampilan kepalangmerahan, P3K, dan kesiapsiagaan untuk anggota.",
      status: "Terbuka untuk anggota",
      is_published: true,
    },
    {
      id: "event-2",
      title: "Pendaftaran anggota baru",
      date: "Awal semester genap",
      time: "Menyesuaikan pengumuman",
      location: "SMKN 4 Banjarmasin",
      description: "Kesempatan untuk siswa aktif yang ingin bertumbuh dalam aksi kemanusiaan.",
      status: "Informasi",
      is_published: true,
    },
  ],
  gallery: [
    {
      id: 1,
      title: "Latgab Pramuka MAN 3 bersama PMR",
      date: "16 Januari 2026",
      category: "Latihan",
      cover: galleryOne[0],
      images: galleryOne,
      description: "Latihan gabungan untuk mempererat silaturahmi dan meningkatkan keterampilan pertolongan pertama.",
      is_published: true,
    },
    {
      id: 2,
      title: "Latgab PMR Wira dan Pramuka",
      date: "17 Januari 2026",
      category: "Latihan",
      cover: galleryTwo[0],
      images: galleryTwo,
      description: "Belajar bekerja sama, berbagi peran, dan tetap tanggap dalam setiap simulasi.",
      is_published: true,
    },
    {
      id: 3,
      title: "Dokumentasi aksi dan kebersamaan :) ",
      date: "2026",
      category: "Aksi sosial",
      cover: "/gudang/gallery/IMG-20260129-WA0031_icpj2a_fqfute.avif",
      images: [
        "/gudang/gallery/IMG-20260129-WA0031_icpj2a_fqfute.avif",
        "/gudang/gallery/IMG-20260129-WA0035_fwkslt_jjng7f.avif",
      ],
      description: "Momen kebersamaan anggota PMR Wira dalam menjalankan semangat humanis, peduli, dan tanggap.",
      is_published: true,
    },
    {
      id: 4,
      title: "Prestasi PMR Wira",
      date: "Arsip kegiatan",
      category: "Prestasi",
      cover: "/gudang/gallery/juara.avif",
      images: ["/gudang/gallery/juara.avif"],
      description: "Apresiasi untuk kerja keras, disiplin, dan semangat belajar seluruh anggota.",
      is_published: true,
    },
    {
      id: 5,
      title: "Latihan keterampilan anggota",
      date: "Arsip kegiatan",
      category: "Latihan",
      cover: "/gudang/gallery/IMG-20260129-WA0037_ywu4kh_eldskn.avif",
      images: ["/gudang/gallery/IMG-20260129-WA0037_ywu4kh_eldskn.avif"],
      description: "Latihan yang membangun kepercayaan diri dan kesiapan untuk membantu sesama.",
      is_published: true,
    },
  ],
  registrations: [
    {
      id: 101,
      name: "Thio",
      email: "kambinghirang3@gmail.com",
      phone: "+62 895-2323-4160",
      class_name: "X RPL 1",
      message: "cuma tes, baru inieh",
      created_at: "2026-07-15T08:30:00Z",
      status: "Baru",
    },
    {
      id: 102,
      name: "Thio",
      email: "kambinghirang4@gmail.com",
      phone: "+62 895-2323-4160",
      class_name: "XI RPL 1",
      message: "tes cet memproses",
      created_at: "2026-07-16T14:15:00Z",
      status: "Diproses",
    },
    {
      id: 103,
      name: "Thio Saputra",
      email: "kambinghirang2@gmail.com",
      phone: "+62 895-2323-4160",
      class_name: "X RPL 1",
      message: "tes tes, diterima :v",
      created_at: "2026-07-16T16:45:00Z",
      status: "Diterima",
    },
  ],
  messages: [
    {
      id: 201,
      name: "Thio Saputra",
      email: "flessan@yahoo.com",
      message: "cuman tes kk ^^",
      created_at: "2026-07-14T10:00:00Z",
      status: "Sudah Dibaca",
    },
    {
      id: 202,
      name: "Thio Saputra",
      email: "tio@cc.cc",
      message: "cumat tes chat",
      created_at: "2026-07-17T09:12:00Z",
      status: "Belum Dibaca",
    },
  ],
  org: {
    periode: "2026/2027",
    advisory: [
      { jabatan: "Wakasek Kesiswaan", nama: "Eka Lisdyawati, M.Pd.", icon: "graduation-cap", deskripsi: "Penanggung jawab umum kebijakan kesiswaan dan pengembangan organisasi sekolah." },
      { jabatan: "Pembina UKS", nama: "Winda Hairani, S.Pd.", icon: "user-round", deskripsi: "Pembimbing teknis operasional dan jembatan antara kurikulum dengan kegiatan PMR." },
    ],
    leaders: [
      { role: "Pembina PMR", nama: "Winda Hairani, S.Pd.", icon: "shield-check", deskripsi: "Guru pembimbing ekstrakurikuler PMR Wira SMKN 4 Banjarmasin." },
      { role: "Ketua", nama: "Adilla Hafiza", icon: "crown", deskripsi: "Pemimpin eksekutif dan penanggung jawab utama seluruh program kerja PMR Wira." },
      { role: "Wakil Ketua", nama: "Assyifa Qolbi", icon: "users", foto: "/gudang/org/wakil_1782458849_771dbdcc.jpeg", deskripsi: "Pendamping ketua dalam koordinasi internal dan pengawasan kinerja." },
      { role: "Sekretaris", nama: "Muhammad Thio Saputra", icon: "notebook-pen", foto: "/gudang/org/wakil_sekretaris_1784116447_104d55b6.jpeg", deskripsi: "Penanggung jawab administrasi dan dokumentasi organisasi." },
      { role: "Bendahara", nama: "Erinne Berlianta Manik", icon: "wallet-cards", deskripsi: "Pengelola keuangan dan transparansi anggaran organisasi." },
    ],
    divisions: [
      { divisi: "Unit Kesehatan Siswa", icon: "heart-pulse", anggota: ["Syifa Maurinjia", "Nazma Az Zahra", "Nahdhah", "Andi Nabilla Ramadani", "Maulidia Hayuningdiah", "Naufa Azmi Khairizqa", "Melsia Oktavia"] },
      { divisi: "Hubungan Masyarakat", icon: "megaphone", foto: "/gudang/org/kord_1784120541_e1bb0122.jpeg", anggota: ["Eva Regina Putri Riyanti", "Lisa Erfina", "Naylah Azkiya", "Rama", "Alia Rahmawati", "Ferdi Herlino", "Almira Fakhriah Hasan"] },
      { divisi: "Pengembangan Sumber Daya Manusia", icon: "users-round", anggota: ["A. Ustman Abdullah", "Kirani", "Halissa Azzahra", "Delya Ananda", "Lionel Abdi Darma W.", "Selviana Dewi", "Muhammad Sultan Ariady"] },
      { divisi: "Sosial Masyarakat", icon: "hand-heart", anggota: ["Nur Aleesya Nashirah", "Nabila Rosydah Zahro", "Zahrah Fitri Aisy", "Wulandari", "Lietya Aisya", "Firy al Humairoh Rahmah", "Sofha Raihana Kamelia"] },
    ],
  },
  contact: {
    sekretariat: {
      alamat: "Ruang UKS, SMKN 4 Banjarmasin",
      telepon: "+62 831-9173-5329",
      email: "pmr@smkn4bjm.sch.id",
      instagram: "pmrskenpatbjm",
      wa_link: "https://wa.me/6283191735329",
      jadwal: [
        { hari: "Senin – Kamis", waktu: "07:00 – 15:00 WITA" },
        { hari: "Jumat", waktu: "07:00 – 11:30 WITA" },
        { hari: "Sabtu – Minggu", waktu: "Tutup" },
      ],
    },
    bergabung: {
      deskripsi: "Siap menjadi bagian dari pergerakan kemanusiaan di sekolah?",
      persyaratan: ["Siswa aktif SMKN 4 Banjarmasin", "Sehat jasmani dan rohani", "Bersedia mengikuti latihan rutin"],
      catatan: "Pendaftaran dibuka setiap awal semester genap.",
      link_wa: "https://wa.me/6283191735329",
    },
  },
  guides: [
    {
      id: "mimisan", title: "Mimisan", icon: "droplets", tone: "red", tag: "Tindakan cepat",
      summary: "Langkah aman menghentikan mimisan sebelum bantuan medis tiba.",
      steps: ["Duduk tegak dan condongkan tubuh sedikit ke depan.", "Pencet bagian lunak hidung selama 5–10 menit tanpa melepasnya.", "Bernapas lewat mulut dan tetap tenang.", "Jika tidak berhenti atau berulang, hubungi petugas medis."],
    },
    {
      id: "pingsan", title: "Pingsan", icon: "accessibility", tone: "yellow", tag: "Keadaan darurat",
      summary: "Bantu korban tetap aman dan periksa responsnya.",
      steps: ["Baringkan korban di tempat aman dan datar.", "Periksa respons dan pernapasan korban.", "Longgarkan pakaian yang ketat dan jangan beri makanan atau minuman saat belum sadar.", "Hubungi bantuan medis jika tidak sadar lebih dari satu menit atau tidak bernapas normal."],
    },
    {
      id: "luka-bakar", title: "Luka bakar", icon: "flame", tone: "orange", tag: "Luka bakar ringan",
      summary: "Dinginkan area luka dan lindungi jaringan dari kerusakan lanjutan.",
      steps: ["Siram dengan air mengalir suhu ruang selama 20 menit.", "Lepas perhiasan sebelum area membengkak, tetapi jangan menarik benda yang menempel.", "Jangan gunakan es, mentega, atau pasta gigi.", "Tutup longgar dengan kain bersih dan cari bantuan untuk luka serius."],
    },
    {
      id: "tersedak", title: "Tersedak", icon: "wind", tone: "blue", tag: "Perlu bantuan",
      summary: "Kenali kondisi tersedak berat dan segera minta bantuan.",
      steps: ["Tanyakan apakah korban tersedak; jika masih bisa batuk, biarkan batuk.", "Jika tidak bisa bernapas atau berbicara, minta orang lain menghubungi 119.", "Berikan dorongan punggung dan perut sesuai pelatihan P3K yang benar.", "Jika korban tidak responsif, mulai RJP bila terlatih dan ikuti instruksi petugas."],
    },
  ],
  faq: [
    { question: "Apa itu PMR?", answer: "Palang Merah Remaja adalah wadah kegiatan siswa untuk belajar nilai kemanusiaan, hidup sehat, pertolongan pertama, dan kesiapsiagaan." },
    { question: "Kapan latihan rutin dilaksanakan?", answer: "Latihan rutin PMR dilaksanakan setiap Kamis pukul 15.00–17.00 WITA di aula atau lapangan sekolah. Jadwal dapat berubah mengikuti kalender sekolah." },
    { question: "Siapa yang bisa bergabung?", answer: "Siswa aktif SMKN 4 Banjarmasin yang sehat jasmani dan rohani serta bersedia mengikuti latihan rutin dapat mendaftar." },
    { question: "Apakah materi P3K bisa menggantikan tenaga medis?", answer: "Tidak. Materi ini bersifat edukatif. Untuk keadaan serius, pastikan lokasi aman dan segera hubungi 119 atau fasilitas kesehatan terdekat." },
  ],
  roster: defaultRoster,
  uks_info: defaultUksInfo,
};
