import {
  Accessibility,
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Bandage,
  BookOpen,
  BookOpenCheck,
  BriefcaseMedical,
  Building2,
  CalendarClock,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  Crown,
  Database,
  Download,
  Droplets,
  Eye,
  FileText,
  Flame,
  Folder,
  GraduationCap,
  HandHeart,
  HardDrive,
  Heart,
  HeartHandshake,
  HeartPulse,
  House,
  Image,
  Images,
  ImagePlus,
  Info,
  Instagram,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  Link2,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Moon,
  Newspaper,
  NotebookPen,
  Package,
  Pencil,
  Phone,
  Pill,
  Plus,
  Quote,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldPlus,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Thermometer,
  Trash2,
  TriangleAlert,
  Trophy,
  Upload,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  WalletCards,
  WifiOff,
  Wind,
  X,
} from "lucide-react";

/**
 * Curated icon set. Content documents reference icons by stable kebab-case
 * names (e.g. "heart-pulse"), so the mapping lives here rather than in content.
 */
const ICONS = {
  accessibility: Accessibility,
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  bandage: Bandage,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "briefcase-medical": BriefcaseMedical,
  building: Building2,
  "calendar-clock": CalendarClock,
  calendar: CalendarDays,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  copy: Copy,
  crown: Crown,
  database: Database,
  download: Download,
  droplets: Droplets,
  eye: Eye,
  "file-text": FileText,
  flame: Flame,
  folder: Folder,
  "graduation-cap": GraduationCap,
  "hand-heart": HandHeart,
  "hard-drive": HardDrive,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  home: House,
  image: Image,
  "image-plus": ImagePlus,
  images: Images,
  info: Info,
  instagram: Instagram,
  landmark: Landmark,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  link: Link2,
  loader: LoaderCircle,
  lock: LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  moon: Moon,
  newspaper: Newspaper,
  "notebook-pen": NotebookPen,
  package: Package,
  pencil: Pencil,
  phone: Phone,
  pill: Pill,
  plus: Plus,
  quote: Quote,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  "shield-plus": ShieldPlus,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  thermometer: Thermometer,
  trash: Trash2,
  "triangle-alert": TriangleAlert,
  trophy: Trophy,
  upload: Upload,
  "user-plus": UserPlus,
  "user-round": UserRound,
  users: Users,
  "users-round": UsersRound,
  "wallet-cards": WalletCards,
  "wifi-off": WifiOff,
  wind: Wind,
  x: X,
};

export const ICON_NAMES = Object.keys(ICONS);

/** Generic icon renderer; unknown names fall back to a friendly sparkle. */
export function Icon({ name, size = 20, strokeWidth = 2.2, className = "", ...rest }) {
  const Component = ICONS[name] || Sparkles;
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" focusable="false" {...rest} />;
}

export default Icon;
